### ISSUE TITLE
Unble to make work with expo

### ISSUE THREAD

**Issue by pabeda-bt** [madsleejensen/react-native-image-sequence#15]
Hello,

Thanks for this great plugin. I'm trying to use it with a Expo project. But I only get a red square.

Here is a screen shot.

![image](https://user-images.githubusercontent.com/15822986/34160228-27ee27e4-e4dd-11e7-9b86-6bd836f5fbf7.png)

The same error occurs with android too. I have linked the plugin.

Here is some warnings that I see:

Warning: Native component for "MKTouchable" does not exist
Warning: Native component for "RCTImageSequence" does not exist

I don't know if the problem occurs because of those warnings?

Thanks

**Comment by julesmoretti** [comment]
+1 on this one, I get:
<img width="328" alt="screen shot 2018-01-18 at 12 22 35 pm" src="https://user-images.githubusercontent.com/744300/35119591-4e8e1894-fc4a-11e7-982f-6743a7995afd.png">

**Comment by matt-oakes** [comment]
This won't work on Expo as it requires native code that Expo does not include. You will need to either eject or Expo will need to include the native code to make this library work.

**Comment by madsleejensen** [comment]
Closing, see @matt-oakes's explanation.
