### ISSUE TITLE
Not working on device (but works on simulator)

### ISSUE THREAD

**Issue by jonzee** [madsleejensen/react-native-image-sequence#3]
It not works on devices (I checked it on iPhone 4s and iPhone 6), but it works on simulator. Any ideas why?

**Comment by madsleejensen** [comment]
Have you updated to latest version? i fixed a similar issue in v0.1.5, if you have a earlier version try to clean project (from xcode) and relink using `react-native unlink react-native-image-sequence` -> `react-native link react-native-image-sequence`

**Comment by jonzee** [comment]
Nope, it's not working, I removed lib, reinstalled, relinked and nothing
- react-native: 0.34.1
- react-native-image-sequence: 0.1.8"
- iPhone 4s
- iOS: 9.3.2

**Comment by jonzee** [comment]
Today I build app on "Release" mode (`cmd + <` -> Build Configuration -> Release) and sequence image works, I install it (throught iTunes) on some devices (iPhone 6s, iPhone 5, iPad) and it works everywhere.
